version: '3.8'

services:
  data-analyzer:
    image: data-analyzer:latest
    container_name: data-analyzer-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:8002"  # Only expose to localhost (NGINX will proxy)
    environment:
      - APP_ENV=prod
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
